name: Build Android APKs

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-main-app:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build Main App
      uses: ArtemSBulgakov/buildozer-action@v1
      with:
        command: buildozer android debug
        buildozer_version: master

    - name: Upload Main APK
      uses: actions/upload-artifact@v4
      with:
        name: DriveLearn-Main-APK
        path: bin/*.apk

  build-reset-app:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Build Reset App
      uses: ArtemSBulgakov/buildozer-action@v1
      with:
        workdir: ./ResetUtility
        command: buildozer android debug
        buildozer_version: master

    - name: Upload Reset APK
      uses: actions/upload-artifact@v4
      with:
        name: DriveLearn-Reset-APK
        path: ResetUtility/bin/*.apk
